In [1]:
import numpy as np

### 1-D Array

In [2]:
n1 = np.array([10,20,30,40])

In [3]:
n1

array([10, 20, 30, 40])

### 2-D Array

In [5]:
n2 = np.array(([10,20,30,40],[40,30,20,10]))
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [6]:
type(n1)

numpy.ndarray

### Zero matrix

In [7]:
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [8]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.full

In [9]:
n5 = np.full((2,2),(10))
n5

array([[10, 10],
       [10, 10]])

### array with range

In [11]:
n6 = np.arange(100,200)
n6

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [12]:
n7 = np.arange(100,201)
n7

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

### range of values with step function with '10' diff from 100 to 200

In [13]:
n8 = np.arange(100,200,10)

In [14]:
n8

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

### Random numbers from 1 to 100 with step 5

In [15]:
n9 = np.random.randint(1,100,5)
n9

array([41, 98, 11, 96, 35])

### change dimension of matrix

In [16]:
n10 = np.array([[10,20,30],[40,50,60]])
n10

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
n10.shape

(2, 3)

In [18]:
n10.shape = (3,2)
n10

array([[10, 20],
       [30, 40],
       [50, 60]])

### STACK

In [19]:
# vstack()

In [21]:
n11 = np.array([10,20,30])
n12 = np.array([40,50,60])

In [24]:
np.vstack((n12,n11))

array([[40, 50, 60],
       [10, 20, 30]])

In [25]:
#hstack()

In [27]:
np.hstack((n12,n11))

array([40, 50, 60, 10, 20, 30])

In [28]:
#column_stack()

In [29]:
np.column_stack((n12,n11))

array([[40, 10],
       [50, 20],
       [60, 30]])

### intersection and difference method

In [30]:
n13 = np.array([10,20,30,40,50,60])
n14 = np.array([50,60,70,80,90])

In [31]:
np.intersect1d(n13,n14)

array([50, 60])

In [32]:
np.setdiff1d(n13,n14)

array([10, 20, 30, 40])

In [33]:
np.setdiff1d(n14,n13)

array([70, 80, 90])

### Addition 

In [34]:
n15 = np.array([10,20])
n16 = np.array([30,40])

In [36]:
np.sum([n15,n16])

100

In [37]:
np.sum([n15,n16], axis=0)

array([40, 60])

In [38]:
np.sum([n15,n16], axis =1)

array([30, 70])

### multiplication

In [40]:
n17 = np.array([10,20,30])
n17 = n17 * 2
n17

array([20, 40, 60])

### Subtraction

In [42]:
n18 = np.array([10,20,30])
n18 = n18 - 1
n18

array([ 9, 19, 29])

### Divide

In [43]:
n19 = np.array([10,20,30])
n19 = n19 / 2
n19

array([ 5., 10., 15.])

### Mean

In [44]:
n20 = np.array([10,20,30,40,50,60])
np.mean(n20)

35.0

### Median

In [45]:
n21 = np.array([5,2,8,9,7,2,1])
np.median(n21)

5.0

### Standard Deviation

In [46]:
np.std(n21)

2.996596709057576

### Matrix

In [47]:
n22 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
n22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
n22[2]

array([7, 8, 9])

In [50]:
n22[:,2]

array([3, 6, 9])

### Transpose

In [51]:
np.transpose(n22)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Matrix Multiplication

In [53]:
n23 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n24 = np.array([[3,2,1],[6,5,4],[9,8,7]])

n23

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
n23.dot(n24)

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [56]:
n24

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [57]:
n24.dot(n23)

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])

### NumPy Save & Load

In [58]:
np.save('save_n23',n23)

In [59]:
n25 = np.load('save_n23.npy')

In [60]:
n25

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])